import type { Stat } from "./research";
export type Discovery = [
  name: string,
  description: string,
  effects: Partial<Record<Stat, number>>,
  icon: string,
  ability?: string,
];

// Specializations join again after either branch. Costs and exclusions live
// in research.ts; every advertised effect has a simulation stat or ability.
export const RUNNER: Discovery[][] = [
  [
    [
      "Warm-up ritual",
      "A proper warm-up gives Ellis a larger stamina reserve for the next run.",
      { stamina: 0.25 },
      "heart",
    ],
    [
      "Long, slow training",
      "Build an economical stride. Running uses less energy, but the comfortable pace is slightly slower.",
      { economy: 0.22, speed: -0.05 },
      "lungs",
    ],
    [
      "Interval training",
      "Short, hard sessions build a larger reserve. The stronger stride costs a little more energy.",
      { stamina: 0.3, economy: -0.08 },
      "wave",
    ],
    [
      "Second wind",
      "Once per run, dropping below 25% stamina opens a 12-second recovery window. Use Steady pace during it to regain energy.",
      { recovery: 0.18 },
      "heart",
      "second-wind",
    ],
    [
      "Marathon conditioning",
      "Extend the endurance specialization: cheaper strides and slower fatigue accumulation.",
      { economy: 0.25, resilience: 0.28 },
      "infinity",
    ],
    [
      "Lactate shuttle",
      "Extend the interval specialization: rebuild speed faster after rough sections and recover more effectively at Recovery pace.",
      { acceleration: 0.4, recovery: 0.3 },
      "cycle",
    ],
    [
      "Heat acclimation",
      "Training in warm conditions slows fatigue. Desert sections also impose half their extra energy cost.",
      { resilience: 0.3 },
      "sun",
      "heat",
    ],
    [
      "Ultra-distance training",
      "Long-term conditioning increases the reserve and reduces fatigue. Keep the earlier endurance or interval specialization.",
      { stamina: 0.55, resilience: 0.4 },
      "mountain",
    ],
  ],
  [
    [
      "Cadence metronome",
      "A regular step rhythm helps Ellis regain speed after rough patches. Acceleration matters each time the route slows him down.",
      { acceleration: 0.28 },
      "wave",
    ],
    [
      "Quiet footfall",
      "Land softly to save energy. The careful stride takes slightly longer to regain speed.",
      { economy: 0.24, acceleration: -0.08 },
      "foot",
    ],
    [
      "Trail-running technique",
      "Short, quick steps rebuild speed on broken surfaces. Reduce the extra energy cost of rough sections by 35%, at a small cost to everyday efficiency.",
      { acceleration: 0.45, economy: -0.06 },
      "mountain",
      "trailcraft",
    ],
    [
      "Rolling start",
      "Start each attempt at half cruising speed. The warm-up jog happens before the measurements begin.",
      { acceleration: 0.25 },
      "arrow",
      "rolling-start",
    ],
    [
      "Clean racing line",
      "The efficient-footfall specialization opens shorter routes. Fast detours keep their speed bonus without their extra energy cost.",
      { economy: 0.12 },
      "route",
      "shortcut",
    ],
    [
      "Negative split",
      "The trail specialization teaches Ellis to finish stronger. Beyond 1 km, cruising speed increases by an extra 15%.",
      { resilience: 0.2 },
      "split",
      "negative-split",
    ],
    [
      "Elastic running form",
      "Use the spring in each landing to carry the next stride. Less energy is lost without forcing a higher pace.",
      { economy: 0.3, acceleration: 0.2 },
      "spring",
    ],
    [
      "Race rehearsal",
      "Practised pace changes improve acceleration, cruising speed and the rate of learning from a run.",
      { acceleration: 0.5, speed: 0.25, xp: 0.25 },
      "flag",
    ],
  ],
  [
    [
      "Proper running shoes",
      "Replace the lab slippers with running soles. Ellis holds a faster pace. This footwear research stays active; collected equipment comes later.",
      { speed: 0.15 },
      "shoe",
    ],
    [
      "Carbon racing soles",
      "A stiff spring plate gives a faster stride, but the unforgiving ride builds fatigue sooner. Choose speed over comfort.",
      { speed: 0.22, resilience: -0.12 },
      "spring",
    ],
    [
      "Ventilated trail kit",
      "A breathable coat and cushioned kit slow fatigue. The comfortable setup sacrifices a little cruising speed.",
      { resilience: 0.38, speed: -0.03 },
      "coat",
    ],
    [
      "Lightweight pockets",
      "Carry the same instruments with less bulk. Increase speed and reduce the energy cost of movement.",
      { speed: 0.1, economy: 0.12 },
      "pack",
    ],
    [
      "Tuned racing foam",
      "Improve the racing soles' rebound. More speed and acceleration, with a further fatigue penalty.",
      { speed: 0.25, acceleration: 0.25, resilience: -0.1 },
      "shoe",
    ],
    [
      "All-weather layers",
      "Improve the trail kit for longer expeditions. A larger reserve and less fatigue help sustain a moderate pace.",
      { stamina: 0.3, resilience: 0.35 },
      "coat",
    ],
    [
      "Servo-assisted knees",
      "Small motors help push through every stride. Rebuild speed faster while spending less energy.",
      { acceleration: 0.45, economy: 0.2 },
      "bolt",
    ],
    [
      "Instrumented hydration vest",
      "Collect richer measurements on long runs. Once supplies are available, each restores 10% more capacity and its cooldown is 15 seconds shorter.",
      { yield: 0.35, stamina: 0.3 },
      "flask",
      "hydration",
    ],
  ],
  [
    [
      "Pocket tailwind",
      "A compact backpack fan adds 0.4 m/s of following wind. It uses energy, so pair its extra speed with efficient running.",
      { wind: 0.2, economy: -0.06 },
      "wind",
    ],
    [
      "Wind-reading ribbons",
      "Airflow markers help adjust the fan direction. More air pushes forward and less energy is wasted.",
      { wind: 0.22, economy: 0.14 },
      "flag",
    ],
    [
      "Trail sampling net",
      "A light collection net gathers useful samples. Increase research yield and equipment discovery odds.",
      { luck: 0.3, yield: 0.12 },
      "pack",
    ],
    [
      "Ducted backpack fan",
      "Guide airflow through a shaped outlet. A stronger tailwind costs additional running energy.",
      { wind: 0.4, economy: -0.08 },
      "wind",
    ],
    [
      "Field survey drone",
      "Record each new biome reached during the attempt. Each one adds 5 RP to the final report.",
      { yield: 0.2 },
      "eye",
      "survey",
    ],
    [
      "Adaptive fan controller",
      "Match fan output to speed instead of running at full power throughout. Improve tailwind and efficiency together.",
      { wind: 0.45, economy: 0.2 },
      "gear",
    ],
    [
      "Sample recognition camera",
      "Recognise unusual finds before Ellis passes them. Improve gear discovery odds and learning from the route.",
      { luck: 0.65, xp: 0.25 },
      "eye",
    ],
    [
      "Personal wind tunnel",
      "A larger ducted rig produces a powerful following wind. Faster movement comes with an energy-efficiency penalty.",
      { wind: 1.1, economy: -0.15 },
      "comet",
    ],
  ],
];

export const PROJECTILE: Discovery[][] = [
  [
    [
      "Smooth river stone",
      "A rounded, balanced stone loses less speed to air resistance and leaves the hand more consistently.",
      { drag: 0.12, stability: 0.15 },
      "stone",
    ],
    [
      "Power throw",
      "A full-body release increases launch speed. The longer wind-up means fewer throws per minute.",
      { launchSpeed: 0.25, reload: -0.15 },
      "spring",
    ],
    [
      "Quick-release throw",
      "A shorter throwing motion prepares the next shot sooner. Each stone leaves the hand slightly slower.",
      { reload: 0.4, launchSpeed: -0.08 },
      "cycle",
    ],
    [
      "Adjustable release angle",
      "Set the next shot's angle between 20° and 65°. Low arcs trade airtime for speed; high arcs keep a stone in the air longer.",
      { stability: 0.18 },
      "route",
      "angle-control",
    ],
    [
      "Skipping stone",
      "The power-throw branch unlocks one ground skip for rocks. The bounce retains 40% of horizontal speed and adds distance after the first landing.",
      { launchSpeed: 0.12 },
      "stone",
      "skip-shot",
    ],
    [
      "Throwing carousel",
      "The quick-release branch feeds the next projectile into position. Shorter preparation and more consistent releases improve repeated tests.",
      { reload: 0.45, stability: 0.25 },
      "gear",
    ],
    [
      "Robotic throwing arm",
      "Repeat the same release with stronger motors. Increase launch velocity and reduce shot-to-shot dispersion.",
      { launchSpeed: 0.35, stability: 0.4 },
      "bolt",
    ],
    [
      "Flywheel launch arm",
      "Store rotational energy between releases. Very high launch speed needs a longer preparation cycle.",
      { launchSpeed: 0.65, reload: -0.15 },
      "comet",
    ],
  ],
  [
    [
      "Paper airplane",
      "Unlock a paper-plane loadout. Wings provide lift: the plane follows a shallower, longer flight than a rock.",
      { lift: 0.12 },
      "plane",
    ],
    [
      "Needle dart fold",
      "Fold narrow wings and a sharp nose. Air resistance falls, but the plane has less lift. Choose a fast, low flight.",
      { drag: 0.35, lift: -0.15 },
      "arrow",
    ],
    [
      "Broad glider wings",
      "Fold a broad wing that stays aloft longer. Extra lift also adds drag. Choose airtime over speed.",
      { lift: 0.5, drag: -0.12 },
      "feather",
    ],
    [
      "Balanced centre of mass",
      "A correctly placed nose weight keeps the wing level and makes the release repeatable.",
      { stability: 0.35, lift: 0.12 },
      "weight",
    ],
    [
      "Laminar dart skin",
      "The dart specialization gains a smooth surface. Stronger drag reduction preserves launch velocity throughout flight.",
      { drag: 0.5, launchSpeed: 0.15 },
      "wind",
    ],
    [
      "Carbon glider frame",
      "The glider specialization gains a stiff, light wing. More lift and predictable flight outweigh a small drag penalty.",
      { lift: 0.55, stability: 0.3, drag: -0.08 },
      "hex",
    ],
    [
      "Retractable flight surfaces",
      "Fold the wing during launch, then open it in flight. Improve lift and reduce the overall drag penalty.",
      { lift: 0.3, drag: 0.3 },
      "plane",
    ],
    [
      "High-altitude airframe",
      "A stable frame and efficient wing keep more launch energy through a long flight.",
      { drag: 0.6, lift: 0.4, stability: 0.3 },
      "cloud",
    ],
  ],
  [
    [
      "Slingshot",
      "Unlock a fixed slingshot station. The band stores energy before release; the scientist stays beside the launcher.",
      { stability: 0.15 },
      "fork",
    ],
    [
      "Heavy tension bands",
      "Store more energy in thick elastic bands. Higher launch velocity takes longer to prepare.",
      { launchSpeed: 0.35, reload: -0.18 },
      "spring",
    ],
    [
      "Compound release",
      "Pulleys and a trigger prepare a consistent shot quickly. Launch velocity is slightly lower than the heavy-band setup.",
      { reload: 0.4, stability: 0.25, launchSpeed: -0.06 },
      "gear",
    ],
    [
      "Charged launch",
      "Every third shot stores extra energy: +18% launch velocity, with 1.5 seconds of extra preparation. The other two shots use the normal cycle.",
      { stability: 0.15 },
      "bolt",
      "charged-launch",
    ],
    [
      "Field cannon",
      "The heavy-band specialization opens a field cannon. Its fixed barrel sends a projectile along a ballistic arc.",
      { launchSpeed: 0.2, reload: -0.12 },
      "cannon",
    ],
    [
      "Rapid-cycle feed",
      "The compound-release specialization loads the next projectile faster. Increase repeatability and Impulse earned from landed shots.",
      { reload: 0.5, stability: 0.3, payload: 0.2 },
      "magnet",
    ],
    [
      "Railgun capacitor bank",
      "Store more launch energy in capacitors. Higher exit speed comes with a slower firing cycle.",
      { launchSpeed: 0.65, reload: -0.2 },
      "bolt",
    ],
    [
      "Orbital mass driver",
      "A long electromagnetic track increases exit velocity and keeps the projectile centred during acceleration.",
      { launchSpeed: 0.8, stability: 0.5 },
      "comet",
    ],
  ],
  [
    [
      "Laser rangefinder",
      "Show a predicted landing range for the selected launcher and angle. Compare it with the actual landing to find the best setup.",
      { xp: 0.15 },
      "eye",
      "rangefinder",
    ],
    [
      "Impact sensors",
      "Measure the energy remaining at landing. Landed shots provide more Impulse and more RP.",
      { payload: 0.3, yield: 0.12 },
      "wave",
    ],
    [
      "High-speed camera",
      "Track the entire flight to improve launch consistency and learning from each test.",
      { stability: 0.35, xp: 0.25 },
      "eye",
    ],
    [
      "Vacuum test chamber",
      "Reduce air resistance around the test path. Projectiles preserve more horizontal velocity.",
      { drag: 0.5 },
      "flask",
    ],
    [
      "Magnetic beam guides",
      "Centred magnetic guides reduce dispersion and provide cleaner impact measurements.",
      { stability: 0.45, payload: 0.2 },
      "magnet",
    ],
    [
      "Linear acceleration stages",
      "Apply launch energy in successive stages. Increase exit speed, with a longer charging cycle.",
      { launchSpeed: 0.6, reload: -0.1 },
      "arrow",
    ],
    [
      "Recovered beam energy",
      "Recover unused charge between tests. Shorten preparation and increase data from completed shots.",
      { reload: 0.45, yield: 0.25 },
      "cycle",
    ],
    [
      "Particle accelerator",
      "Unlock the accelerator loadout. A fixed emitter launches a small packet at extreme speed; beam stability improves shot consistency.",
      { launchSpeed: 0.5, stability: 0.5, payload: 0.35 },
      "orbit",
    ],
  ],
];

export const WHEELS: Discovery[][] = [
  [
    [
      "Greased bearings",
      "Lubricated bearings reduce rolling losses and slightly increase cruising speed.",
      { economy: 0.18, speed: 0.06 },
      "gear",
    ],
    [
      "Short gearing",
      "Lower gear ratios regain speed quickly after a rough section, but reduce cruising speed.",
      { acceleration: 0.6, speed: -0.08 },
      "cycle",
    ],
    [
      "Tall gearing",
      "Higher gear ratios increase cruising speed. Acceleration is slower after every speed loss.",
      { speed: 0.22, acceleration: -0.12 },
      "gear",
    ],
    [
      "Limited-slip axle",
      "Keep force on the wheel with grip. Acceleration improves and rough sections cause less fatigue.",
      { resilience: 0.25, acceleration: 0.25 },
      "split",
    ],
    [
      "Sequential gearbox",
      "Extend short gearing with faster shifts. Accelerate much faster between route obstacles.",
      { acceleration: 0.55, economy: 0.12 },
      "arrow",
    ],
    [
      "Overdrive transmission",
      "Extend tall gearing with an extra cruising ratio. More speed comes with another acceleration penalty.",
      { speed: 0.3, acceleration: -0.1 },
      "gear",
    ],
    [
      "Magnetic bearings",
      "Reduce mechanical contact inside the hubs. Lower rolling losses preserve energy at speed.",
      { economy: 0.45, speed: 0.2 },
      "magnet",
    ],
    [
      "Direct-drive hubs",
      "Put the drive at each wheel. Increase speed and response without losses through long transmission paths.",
      { speed: 0.4, acceleration: 0.4, economy: 0.3 },
      "infinity",
    ],
  ],
  [
    [
      "Flexible deck",
      "A flexible deck absorbs bumps instead of passing every shock to the rider.",
      { resilience: 0.2, stamina: 0.12 },
      "board",
    ],
    [
      "Soapbox cart",
      "Unlock a seated cart. Its stable chassis carries more reserve, but its weight slows acceleration.",
      { stamina: 0.25, resilience: 0.2, acceleration: -0.12 },
      "cart",
    ],
    [
      "Bicycle",
      "Unlock a bicycle. Efficient pedals and a light frame improve acceleration, with a smaller energy reserve.",
      { economy: 0.2, acceleration: 0.25, stamina: -0.08 },
      "bike",
    ],
    [
      "Reinforced chassis",
      "Strengthen the chosen frame. Rough sections build less fatigue and the team can carry more energy.",
      { stamina: 0.18, resilience: 0.25 },
      "hex",
    ],
    [
      "Streamlined cart shell",
      "The cart specialization gains an enclosed shell. Reduce energy losses and increase comfortable speed.",
      { economy: 0.3, speed: 0.2 },
      "feather",
    ],
    [
      "Land-speed car",
      "The lightweight specialization opens a land-speed car. A larger energy reserve supports the faster vehicle.",
      { stamina: 0.35 },
      "car",
    ],
    [
      "Rocket sled",
      "Unlock a rocket-driven sled. A rigid chassis resists fatigue from sustained high-speed testing.",
      { resilience: 0.4 },
      "comet",
    ],
    [
      "Maglev prototype",
      "Reduce ground contact using magnetic support. Lower losses improve efficiency and cruising speed.",
      { economy: 0.5, speed: 0.35 },
      "orbit",
    ],
  ],
  [
    [
      "Efficient push-off",
      "A better push-off transfers more of the rider's effort into the skateboard's motion.",
      { economy: 0.15, acceleration: 0.12 },
      "foot",
    ],
    [
      "Large battery pack",
      "Carry more stored energy. The extra mass reduces acceleration.",
      { stamina: 0.4, acceleration: -0.12 },
      "pack",
    ],
    [
      "High-output motor",
      "A compact motor accelerates quickly. Its high output uses energy less efficiently.",
      { acceleration: 0.6, economy: -0.12 },
      "bolt",
    ],
    [
      "Battery cooling",
      "Keep the battery within its useful temperature range. Fatigue builds slower and Recovery pace restores more energy.",
      { resilience: 0.35, recovery: 0.3 },
      "snow",
    ],
    [
      "Regenerative braking",
      "The long-range setup recovers more energy at Recovery pace and spends less energy while moving.",
      { recovery: 0.45, economy: 0.15 },
      "cycle",
    ],
    [
      "Turbine drive",
      "The high-output setup gains a turbine. Faster cruising comes with an efficiency penalty.",
      { speed: 0.4, economy: -0.15 },
      "wind",
    ],
    [
      "Rocket fuel chemistry",
      "A more efficient propellant stores more usable energy in the same tank.",
      { stamina: 0.45, economy: 0.3 },
      "flask",
    ],
    [
      "Fusion drive",
      "A compact reactor provides a stronger drive and a larger usable energy reserve for long-distance tests.",
      { speed: 0.5, stamina: 0.5, resilience: 0.3 },
      "sun",
    ],
  ],
  [
    [
      "Tyre compound",
      "Softer tyres improve grip and acceleration on uneven surfaces.",
      { acceleration: 0.18, resilience: 0.12 },
      "wheel",
    ],
    [
      "Grip telemetry",
      "Record wheel slip as it happens. Learn faster and bring home more useful research.",
      { xp: 0.25, yield: 0.18 },
      "wave",
    ],
    [
      "Active suspension",
      "Let the wheels follow bumps while the chassis stays stable. Reduce fatigue and movement losses.",
      { resilience: 0.35, economy: 0.12 },
      "spring",
    ],
    [
      "Ground-effect bodywork",
      "Shape airflow beneath the vehicle to maintain grip. A stable chassis can sustain a faster pace.",
      { resilience: 0.2, speed: 0.2 },
      "feather",
    ],
    [
      "Traction controller",
      "Adjust power when grip changes. Regain speed faster and waste less energy on wheel slip.",
      { economy: 0.3, acceleration: 0.25 },
      "route",
    ],
    [
      "Ceramic brakes",
      "Heat-resistant brakes make pace changes repeatable. Recovery improves and the vehicle can hold a faster cruising pace.",
      { speed: 0.25, recovery: 0.35 },
      "wheel",
    ],
    [
      "Roadside lidar",
      "Spot useful equipment before it passes the vehicle. More finds and cleaner route measurements improve each attempt.",
      { luck: 0.7, yield: 0.25 },
      "eye",
    ],
    [
      "Inertial dampers",
      "Reduce loads transferred to the chassis during long tests. Less fatigue supports a higher sustained speed.",
      { resilience: 0.6, speed: 0.3 },
      "orbit",
    ],
  ],
];

export const SHARED: Discovery[][] = [
  [
    [
      "Field notebooks",
      "Record the conditions alongside each measurement. All programs bring home more RP.",
      { yield: 0.12 },
      "book",
    ],
    [
      "Peer review",
      "Compare independent measurements before accepting a result. Research yield and learning improve in every program.",
      { yield: 0.2, xp: 0.15 },
      "eye",
    ],
    [
      "Open science",
      "Share methods between the teams. Increase research yield and the chance of noticing useful equipment.",
      { yield: 0.35, luck: 0.2 },
      "flask",
    ],
  ],
  [
    [
      "Sample archive",
      "Label recovered equipment and samples. Improve the chance of identifying useful finds.",
      { luck: 0.18 },
      "pack",
    ],
    [
      "Field logistics",
      "Unlock three supplies per running or wheeled attempt. Each restores energy; projectile tests use a launcher cycle instead.",
      { yield: 0.12 },
      "pack",
      "supplies",
    ],
    [
      "Mobile workshop",
      "Service equipment between tests. Improve runner and vehicle recovery, and shorten projectile preparation.",
      { recovery: 0.3, reload: 0.3 },
      "gear",
    ],
  ],
  [
    [
      "Team coaching",
      "Review each attempt with the team. Increase experience earned in every program.",
      { xp: 0.2 },
      "heart",
    ],
    [
      "Motion analysis",
      "Learn faster, accelerate runners and wheels faster, and launch projectiles more consistently.",
      { xp: 0.25, acceleration: 0.18, stability: 0.18 },
      "wave",
    ],
    [
      "Experiment planning",
      "Use earlier results to choose the next conditions. Improve learning and the amount of RP earned.",
      { xp: 0.4, yield: 0.2 },
      "book",
    ],
  ],
  [
    [
      "Field timing instruments",
      "Accurate split and flight times turn each test into more useful research data.",
      { yield: 0.15 },
      "wave",
    ],
    [
      "Weather station",
      "Measure airflow before each attempt. Better fan settings help runners; calibrated release settings improve projectile consistency.",
      { wind: 0.25, stability: 0.25 },
      "flag",
    ],
    [
      "Lightweight materials",
      "Stronger, lighter materials reduce runner and wheel energy costs; streamlined projectiles lose less speed to drag.",
      { economy: 0.2, drag: 0.2 },
      "hex",
    ],
  ],
];
