import type { Stat } from "./research";
export type Discovery = [
  name: string,
  story: string,
  effects: Partial<Record<Stat, number>>,
  icon: string,
  ability?: string,
];
export const RUNNER: Discovery[][] = [
  [
    [
      "Warm-up ritual",
      "Convince the muscles this is a scientific expedition, not a fire drill.",
      { stamina: 0.16, acceleration: 0.12 },
      "heart",
    ],
    [
      "Diaphragm breathing",
      "Less panic per breath. More road per lungful.",
      { economy: 0.18, recovery: 0.12 },
      "lungs",
    ],
    [
      "Salt & water",
      "Keep the electrical system inside the scientist conducting.",
      { stamina: 0.22, resilience: 0.14 },
      "drop",
    ],
    [
      "Second wind",
      "Below 25% stamina, steady pace slowly restores energy for 12 seconds. Once per run.",
      { recovery: 0.18 },
      "heart",
      "second-wind",
    ],
    [
      "Lactate shuttle",
      "Recycle yesterday's muscular complaints into tomorrow's forward motion.",
      { economy: 0.24, acceleration: 0.18 },
      "cycle",
    ],
    [
      "Heat acclimation",
      "Desert conditions lose half their extra stamina penalty.",
      { resilience: 0.24 },
      "sun",
      "heat",
    ],
    [
      "Elastic tendons",
      "Store landing energy and return it at take-off.",
      { economy: 0.28, speed: 0.16 },
      "spring",
    ],
    [
      "The unreasonable marathon",
      "Fatigue resistance, a larger reserve, and absolutely no respectable stopping point.",
      { stamina: 0.55, resilience: 0.4, recovery: 0.25 },
      "infinity",
    ],
  ],
  [
    [
      "Cadence metronome",
      "A pocket-sized drummer that never requests a break.",
      { acceleration: 0.28, economy: 0.08 },
      "wave",
    ],
    [
      "Quiet footfall",
      "Stop paying an energy tax every time a foot meets the ground.",
      { economy: 0.22 },
      "foot",
    ],
    [
      "Hill technique",
      "Short steps, high knees. Alpine terrain loses half its extra stamina penalty.",
      { acceleration: 0.18, resilience: 0.16 },
      "mountain",
      "altitude",
    ],
    [
      "Rolling start",
      "Begin each new run already moving at half your cruising speed.",
      { acceleration: 0.25 },
      "arrow",
      "rolling-start",
    ],
    [
      "Corner cutting",
      "Fast-route detours retain their speed bonus but lose their extra energy cost.",
      { speed: 0.12 },
      "route",
      "shortcut",
    ],
    [
      "Negative split",
      "After 1 km, gain another 15% cruising speed.",
      { economy: 0.15 },
      "split",
      "negative-split",
    ],
    [
      "Flow state",
      "Steady running becomes both cheaper and easier to learn from.",
      { economy: 0.3, xp: 0.4 },
      "wave",
    ],
    [
      "Perfect motion",
      "Less braking, better launch, and fewer arguments with gravity.",
      { acceleration: 0.6, speed: 0.3, resilience: 0.2 },
      "orbit",
    ],
  ],
  [
    [
      "Proper running shoes",
      "Actual running shoes. The lab slippers have been respectfully retired.",
      { speed: 0.08, economy: 0.12 },
      "shoe",
    ],
    [
      "Springy midsoles",
      "A little trampoline under each foot. The ethics panel was surprisingly relaxed.",
      { acceleration: 0.25, economy: 0.14 },
      "spring",
    ],
    [
      "Ventilated lab coat",
      "Science remains professional. Armpits become habitable.",
      { resilience: 0.28, recovery: 0.1 },
      "coat",
    ],
    [
      "Reinforced hydration vest",
      "Supplies restore an extra 10% capacity and become ready 15 seconds sooner.",
      { stamina: 0.18 },
      "pack",
      "hydration",
    ],
    [
      "Flywheel backpack",
      "Store momentum in a spinning disc. Do not turn around suddenly.",
      { speed: 0.22, acceleration: 0.25 },
      "gear",
    ],
    [
      "Servo-assisted knees",
      "A powered push through every stride, without replacing the knees with kangaroo parts.",
      { acceleration: 0.45, economy: 0.2 },
      "bolt",
    ],
    [
      "Inertial insoles",
      "The shoes remember where forward is even when the scientist doesn't.",
      { speed: 0.3, resilience: 0.22 },
      "shoe",
    ],
    [
      "Walking laboratory",
      "Carry the experiment with you; collect richer data from every metre.",
      { yield: 0.4, stamina: 0.3, luck: 0.2 },
      "flask",
    ],
  ],
  [
    [
      "Pocket tailwind",
      "An extremely small fan. An extremely confident grant application.",
      { wind: 0.2 },
      "wind",
    ],
    [
      "Wind-reading ribbons",
      "Find the favourable gusts rather than wrestling every breeze.",
      { wind: 0.22, economy: 0.14 },
      "flag",
    ],
    [
      "Sample magnet",
      "Tiny interesting things now find you interesting too.",
      { luck: 0.3, yield: 0.12 },
      "magnet",
    ],
    [
      "Pressure corridor",
      "Shape a moving pocket of air around the runner.",
      { wind: 0.4, economy: 0.2 },
      "wind",
    ],
    [
      "Field survey drone",
      "Each newly reached biome adds 20 RP to the final report.",
      { yield: 0.2 },
      "eye",
      "survey",
    ],
    [
      "Atmospheric bargaining",
      "Negotiate a better relationship with the weather. Bring biscuits.",
      { wind: 0.6, resilience: 0.2 },
      "cloud",
    ],
    [
      "Lucky coincidence engine",
      "A machine that makes the improbable somewhat less improbable.",
      { luck: 0.75, xp: 0.25 },
      "spark",
    ],
    [
      "The following wind",
      "Enough tailwind to make the horizon look nervous.",
      { wind: 1.1, economy: 0.25 },
      "comet",
    ],
  ],
];
export const PROJECTILE: Discovery[][] = [
  [
    [
      "Smooth river stone",
      "A balanced starting mass, with fewer accidental corners.",
      { speed: 0.1, acceleration: 0.16 },
      "stone",
    ],
    [
      "Wrist mechanics",
      "Stop launching half the force into the researcher's elbow.",
      { economy: 0.2, acceleration: 0.2 },
      "spring",
    ],
    [
      "Counterweight sling",
      "Let stored weight do some of the strenuous work.",
      { stamina: 0.3, resilience: 0.12 },
      "weight",
    ],
    [
      "Rotational launch",
      "Build speed before release instead of apologising after it.",
      { acceleration: 0.45, speed: 0.12 },
      "cycle",
    ],
    [
      "Elastic release",
      "Time the release to the stored tension.",
      { economy: 0.3, speed: 0.18 },
      "wave",
    ],
    [
      "Robotic throwing arm",
      "A tireless assistant that only occasionally throws the clipboard.",
      { resilience: 0.4, recovery: 0.25 },
      "bolt",
    ],
    [
      "Sonic release",
      "Compress the launch into a much shorter, much louder moment.",
      { acceleration: 0.7, speed: 0.25 },
      "comet",
    ],
    [
      "Orbital throw",
      "Every launch now has a slightly worrying destination.",
      { speed: 0.45, stamina: 0.35, luck: 0.25 },
      "orbit",
    ],
  ],
  [
    [
      "Paper airplane",
      "Fold a wing. Discover that falling can be postponed.",
      { economy: 0.12 },
      "plane",
    ],
    [
      "Folded winglets",
      "Keep more of the air doing useful things near the wingtips.",
      { economy: 0.23, wind: 0.12 },
      "feather",
    ],
    [
      "Glider profile",
      "Trade a little launch force for a lot more time aloft.",
      { stamina: 0.3, wind: 0.2 },
      "plane",
    ],
    [
      "Carbon airframe",
      "More structure, less mass, fewer soggy experiments.",
      { acceleration: 0.3, economy: 0.2 },
      "hex",
    ],
    [
      "Laminar flow",
      "Persuade the air to stop forming committees behind the projectile.",
      { economy: 0.38, wind: 0.2 },
      "wind",
    ],
    [
      "Hypersonic shape",
      "A nose cone that asks fewer questions of the atmosphere.",
      { speed: 0.4, resilience: 0.25 },
      "arrow",
    ],
    [
      "Plasma envelope",
      "Build a softer path through some very hard air.",
      { wind: 0.8, economy: 0.25 },
      "sun",
    ],
    [
      "Vacuum tunnel",
      "Remove the air from the equation. It was being difficult.",
      { wind: 1.2, speed: 0.3 },
      "orbit",
    ],
  ],
  [
    [
      "Slingshot",
      "Two prongs, an elastic band, and an incident report waiting to happen.",
      { acceleration: 0.15 },
      "fork",
    ],
    [
      "Tension bands",
      "Store more launch energy without borrowing more scientists.",
      { stamina: 0.24, acceleration: 0.2 },
      "spring",
    ],
    [
      "Compound launcher",
      "A set of pulleys converts patience into acceleration.",
      { acceleration: 0.35, economy: 0.18 },
      "gear",
    ],
    [
      "Trebuchet mathematics",
      "A surprisingly respectable answer to an unreasonable question.",
      { yield: 0.3, speed: 0.15 },
      "route",
    ],
    [
      "Field cannon",
      "The neighbours have been informed. They are not reassured.",
      { resilience: 0.25 },
      "cannon",
    ],
    [
      "Coilgun cooling",
      "Recover between magnetic pulses before anything melts.",
      { recovery: 0.6, economy: 0.2 },
      "magnet",
    ],
    [
      "Railgun capacitors",
      "Charge slowly. Spend it extremely quickly.",
      { stamina: 0.5, acceleration: 0.5 },
      "bolt",
    ],
    [
      "Orbital mass driver",
      "Scale the launcher until the word 'field' becomes misleading.",
      { speed: 0.5, economy: 0.4 },
      "comet",
    ],
  ],
  [
    [
      "Motion capture",
      "Measure the interesting part instead of the splash afterwards.",
      { yield: 0.18, xp: 0.15 },
      "eye",
    ],
    [
      "Impact chamber",
      "A controlled landing provides considerably more useful evidence.",
      { yield: 0.28, resilience: 0.12 },
      "hex",
    ],
    [
      "Magnetic lenses",
      "Focus the beam. Stop irradiating the filing cabinet.",
      { acceleration: 0.3, luck: 0.2 },
      "magnet",
    ],
    [
      "Vacuum chamber",
      "Fewer collisions with molecules that weren't invited.",
      { economy: 0.35 },
      "flask",
    ],
    [
      "Particle injector",
      "Feed the machine something smaller than the intern's lunch.",
      { stamina: 0.3, xp: 0.3 },
      "drop",
    ],
    [
      "Linear accelerator",
      "Put the energy stages in a line and dare the particle to slow down.",
      { acceleration: 0.65, speed: 0.22 },
      "arrow",
    ],
    [
      "Synchrotron",
      "Round and round, increasingly quickly, on purpose.",
      { economy: 0.4, yield: 0.4 },
      "cycle",
    ],
    [
      "Particle accelerator",
      "Matter moves. The grant committee stands very far away.",
      { resilience: 0.5, luck: 0.4 },
      "orbit",
    ],
  ],
];
export const WHEELS: Discovery[][] = [
  [
    [
      "Greased bearings",
      "Remove the grinding noise. Discover it was also slowing you down.",
      { economy: 0.18, speed: 0.06 },
      "gear",
    ],
    [
      "Chain drive",
      "Turn effort into motion through something more reliable than optimism.",
      { acceleration: 0.3 },
      "cycle",
    ],
    [
      "Precision gears",
      "Pick the right ratio for getting moving and staying moving.",
      { economy: 0.2, speed: 0.12 },
      "gear",
    ],
    [
      "Limited-slip axle",
      "Keep useful force going to the wheel that can use it.",
      { resilience: 0.25, acceleration: 0.25 },
      "split",
    ],
    [
      "Sequential gearbox",
      "Less time between useful ratios.",
      { acceleration: 0.45, speed: 0.16 },
      "arrow",
    ],
    [
      "Electric differential",
      "Two wheels cooperate, despite having different opinions.",
      { economy: 0.3, resilience: 0.25 },
      "bolt",
    ],
    [
      "Magnetic bearings",
      "Reduce contact by making contact optional.",
      { economy: 0.45, speed: 0.2 },
      "magnet",
    ],
    [
      "Frictionless drive",
      "The paperwork claims 'almost frictionless'. The wheels disagree.",
      { speed: 0.4, acceleration: 0.4, economy: 0.3 },
      "infinity",
    ],
  ],
  [
    [
      "Flexible deck",
      "A board that absorbs bumps instead of passing them to the scientist.",
      { resilience: 0.2, stamina: 0.12 },
      "board",
    ],
    [
      "Soapbox cart",
      "Add a seat and a steering wheel. Remove most of the dignity.",
      { stamina: 0.18 },
      "cart",
    ],
    [
      "Bicycle",
      "Two wheels, working pedals, and a bell labelled emergency siren.",
      { economy: 0.15 },
      "bike",
    ],
    [
      "Racing kart",
      "Lower the centre of gravity and raise the insurance premium.",
      { acceleration: 0.3, resilience: 0.18 },
      "cart",
    ],
    [
      "Streamlined shell",
      "Fewer square corners for the air to object to.",
      { wind: 0.4, economy: 0.2 },
      "feather",
    ],
    [
      "Land-speed car",
      "A chassis designed around the phrase 'a bit faster'.",
      { stamina: 0.3 },
      "car",
    ],
    [
      "Rocket sled",
      "The steering system has been replaced with a strongly worded prayer.",
      { resilience: 0.4 },
      "comet",
    ],
    [
      "Maglev prototype",
      "A chassis that maintains a professional distance from the ground.",
      { economy: 0.5, wind: 0.6 },
      "orbit",
    ],
  ],
  [
    [
      "Efficient pedals",
      "A better lever for the original power source: legs.",
      { economy: 0.15, acceleration: 0.12 },
      "foot",
    ],
    [
      "Flywheel reservoir",
      "Save useful momentum for the next acceleration.",
      { stamina: 0.25, acceleration: 0.18 },
      "cycle",
    ],
    [
      "Electric motor",
      "Introduce a power source that never asks about lunch.",
      { acceleration: 0.45 },
      "bolt",
    ],
    [
      "Battery cooling",
      "The battery may work hard, but it no longer cooks itself.",
      { resilience: 0.35, recovery: 0.3 },
      "snow",
    ],
    [
      "Regenerative braking",
      "Recovery pace restores energy 45% faster.",
      { recovery: 0.45, economy: 0.15 },
      "cycle",
    ],
    [
      "Turbine drive",
      "A small weather event, connected to the wheels.",
      { speed: 0.35, wind: 0.25 },
      "wind",
    ],
    [
      "Rocket fuel chemistry",
      "Get more push from the same alarming canister.",
      { stamina: 0.45, economy: 0.3 },
      "flask",
    ],
    [
      "Fusion drive",
      "A tiny star with a very specific commuting preference.",
      { speed: 0.5, recovery: 0.5, resilience: 0.3 },
      "sun",
    ],
  ],
  [
    [
      "Tyre compound",
      "A better grip on reality. And asphalt.",
      { acceleration: 0.18, resilience: 0.12 },
      "wheel",
    ],
    [
      "Grip telemetry",
      "Record the moments just before the exciting noises.",
      { xp: 0.25, yield: 0.18 },
      "wave",
    ],
    [
      "Active suspension",
      "Let the wheels follow the bumps while the scientist ignores them.",
      { resilience: 0.35, economy: 0.12 },
      "spring",
    ],
    [
      "Ground effect",
      "Invite the air to hold the vehicle down for a change.",
      { wind: 0.3, speed: 0.2 },
      "feather",
    ],
    [
      "Stability control",
      "Preserve speed by avoiding dramatic sideways experiments.",
      { economy: 0.3, acceleration: 0.25 },
      "route",
    ],
    [
      "Ceramic brakes",
      "Safer deceleration gives the test team confidence to go faster.",
      { speed: 0.25, recovery: 0.35 },
      "wheel",
    ],
    [
      "Roadside lidar",
      "Spot useful findings before they become a blur.",
      { luck: 0.7, yield: 0.25 },
      "eye",
    ],
    [
      "Inertial control",
      "The passenger's stomach is no longer the limiting factor.",
      { resilience: 0.6, speed: 0.3 },
      "orbit",
    ],
  ],
];
export const SHARED: Discovery[][] = [
  [
    [
      "Field notebooks",
      "Write down the results before calling them a breakthrough.",
      { yield: 0.12 },
      "book",
    ],
    [
      "Peer review",
      "A second scientist notices the decimal point.",
      { yield: 0.2, xp: 0.15 },
      "eye",
    ],
    [
      "Open science",
      "Every program benefits when the team stops hoarding notebooks.",
      { yield: 0.35, luck: 0.2 },
      "flask",
    ],
  ],
  [
    [
      "Sample archive",
      "Keep the strange findings instead of storing sandwiches on top of them.",
      { luck: 0.18 },
      "pack",
    ],
    [
      "Field logistics",
      "Unlock three supplies per run. Support crews finally get a budget.",
      { yield: 0.12 },
      "pack",
      "supplies",
    ],
    [
      "Mobile workshop",
      "Repairs, fresh batteries, and a significantly less worrying toolbox.",
      { recovery: 0.3, resilience: 0.25 },
      "gear",
    ],
  ],
  [
    [
      "Team coaching",
      "Turn the mistakes into lessons instead of departmental gossip.",
      { xp: 0.2 },
      "heart",
    ],
    [
      "Shared techniques",
      "Let the throwing team learn something from the running team.",
      { xp: 0.25, acceleration: 0.18 },
      "wave",
    ],
    [
      "Collective intelligence",
      "The team becomes smarter than its least caffeinated member.",
      { xp: 0.4, economy: 0.2 },
      "spark",
    ],
  ],
  [
    [
      "Precision tools",
      "Measure once. Build something that actually fits.",
      { acceleration: 0.15 },
      "tool",
    ],
    [
      "Weather station",
      "Know which way the wind intends to be annoying.",
      { wind: 0.25, resilience: 0.1 },
      "flag",
    ],
    [
      "Unified engineering",
      "Pool the equipment knowledge across all three programs.",
      { speed: 0.2, economy: 0.2, luck: 0.2 },
      "hex",
    ],
  ],
];
